### PR TITLE
🐛 Improve search results

### LINKED ISSUE #50: Search only works for first word in name
https://twitter.com/SuperbassWP/status/1484911479031844871?s=20

### PR DESCRIPTION
**Pull request by pajowu**
Fixes #50

### CODE REVIEW

**Comment by m0nac0** [comment]
Testing the example mentioned in #50, searching for "Clinitest" now works with this PR, but searching for "Siemens" or "Healthineers" still doesn't work.

**Comment by so-langsam** [comment]
I tried to have a look at the bug (searching for 'siemens' doesn't work) and I don't have a clue why it's not working.

But - maybe this is useful for somebody - I noticed, that the version of fuse.js that is in use is two years old. Fuse.js comes in as a dependency of react-select-search which depends on fuse.js in version "^3.4.5" which resolves to version "3.6.1".

The most current version of fuse.js is 6.5.3

Sadly there is no newer version of react-select-search (then the one included) that depends on a more current version of fuse.js.

**Comment by pajowu** [comment]
OMG THANK YOU SO MUCH!!!! That's exactly the issue why our search didn't work properly

**Comment by pajowu** [comment]
This is no longer needed thanks to @so-langsam finding which I fixed in #63

**Pull request closed without merging**
